# Generated by Django 5.2.3 on 2025-07-21 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jugadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(upload_to='qr_carnets/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Jugadores.jugador')),
            ],
        ),
    ]
