# Generated by Django 5.2 on 2025-06-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
    ]
