# Generated by Django 5.2.3 on 2025-07-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Temporadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_programada', models.DateField()),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temporadas.temporada')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('temporada', 'numero')},
            },
        ),
    ]
