# Generated by Django 5.2.3 on 2025-07-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0003_alter_equipo_logo'),
        ('Fechas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='Equipos.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='Equipos.equipo')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fechas.fecha')),
            ],
        ),
    ]
