# Generated by Django 5.2.3 on 2025-07-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreliga', models.CharField(max_length=100)),
                ('nombretorneo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('reglamento', models.FileField(blank=True, null=True, upload_to='reglamentos/')),
            ],
        ),
    ]
