# Generated by Django 5.2.3 on 2025-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temporadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='reglamento',
            field=models.FileField(blank=True, null=True, upload_to='reglamentos/'),
        ),
    ]
