# Generated by Django 5.2.3 on 2025-07-16 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0002_participacionequipo'),
        ('Jugadores', '0001_initial'),
        ('Temporadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traspaso', models.DateField()),
                ('desde_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='Equipos.equipo')),
                ('hacia_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='Equipos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jugadores.jugador')),
                ('temporada_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temporadas.temporada')),
            ],
        ),
    ]
