# Generated by Django 5.2.3 on 2025-07-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jugadores', '0002_jugador_cedula'),
        ('Temporadas', '0001_initial'),
        ('Traspasos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traspaso',
            unique_together={('jugador', 'temporada_origen')},
        ),
    ]
