# Generated by Django 5.2.3 on 2025-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='logos/')),
                ('fundacion', models.DateField()),
                ('presidente', models.CharField(max_length=100)),
            ],
        ),
    ]
