# Generated by Django 5.2.3 on 2025-07-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
        ('Temporadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temporadas.temporada')),
            ],
            options={
                'unique_together': {('equipo', 'temporada')},
            },
        ),
    ]
