# Generated by Django 5.2 on 2025-07-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('experiencia', models.PositiveIntegerField(help_text='Años de experiencia')),
            ],
        ),
    ]
