# Generated by Django 5.2.3 on 2025-07-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carnets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.TextField(max_length=100)),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carnets.carnet')),
            ],
        ),
    ]
