# Generated by Django 5.2.3 on 2025-07-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipos', '0001_initial'),
        ('Temporadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='jugadores/')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
                ('posicion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Temporadas.temporada')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jugadores.jugador')),
            ],
            options={
                'unique_together': {('equipo', 'temporada', 'numero'), ('jugador', 'temporada')},
            },
        ),
    ]
